name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: "lts/fermium"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test
